# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_auto_20171008_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='tipo',
            field=models.CharField(choices=[('cuadro', 'cuadro'), ('escultura', 'escultura')], default='cuadro', max_length=255),
        ),
    ]
