# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-04 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_obra_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to=b'')),
                ('image2', models.ImageField(blank=True, upload_to=b'')),
            ],
        ),
    ]
