# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_historia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='obra',
            name='tipo',
            field=models.CharField(choices=[('rectores', 'rectores'), ('hace30', 'hace30'), ('cancilleres', 'cancilleres'), ('arte', 'arte'), ('objetos', 'objetos'), ('emblemas', 'emblemas'), ('promotores', 'promotores'), ('flora', 'flora'), ('fauna', 'fauna')], default='rectores', max_length=255),
        ),
    ]
