# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_auto_20171120_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='nombre',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
